<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
	String message = request.getParameter("message");
	String DBType = request.getParameter("DBType");
	String hostIp = request.getParameter("hostIp");
	String port = request.getParameter("port");
	String DBUser = request.getParameter("DBUser");
	String DBPassword = request.getParameter("DBPassword");
	String schema = request.getParameter("schema");
	String tableName = request.getParameter("tableName");
	String where = request.getParameter("where");
	String target = request.getParameter("target");
	String columnSplit = request.getParameter("columnSplit");
	String rowSplit = request.getParameter("rowSplit");
	String isIncremental = request.getParameter("isIncremental");
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Generated by Apache Maven Doxia at 2016-11-13 -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Sqoop - Apache Sqoop 1.44.6</title>
<style type="text/css" media="all">
@import url("./css/maven-base.css");

@import url("./css/maven-theme.css");

@import url("./css/site.css");
</style>
<link rel="stylesheet" href="./css/print.css" type="text/css"
	media="print" />
<meta name="Date-Revision-yyyymmdd" content="20161113" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body class="composite">
	<div id="banner">
		<a href="http://sqoop.apache.org/" id="bannerLeft"> <img
			src="images/sqoop-logo.png" alt="" />
		</a> <a href="http://www.apache.org/" id="bannerRight"> <img
			src="http://www.apache.org/images/asf_logo_wide.png" alt="" />
		</a>
		<div class="clear">
			<hr />
		</div>
	</div>
	<div id="breadcrumbs">

		<div class="xleft">
			<a href="<%=path%>/index.jsp" class="externalLink">首页</a> &gt; <a
				href="<%=path%>/savedJobList" class="externalLink">作业状态/已保存作业</a>
		</div>
		<div class="xright">
			<a href="http://wiki.apache.org/sqoop" class="externalLink">Wiki</a>
			| <a href="https://svn.apache.org/repos/asf/sqoop/"
				class="externalLink">SVN</a> &nbsp;| Last Modified: 2016-04-15
			&nbsp;| Version: 1.44.6
		</div>
		<div class="clear">
			<hr />
		</div>
	</div>
	<%@include file="/left.jsp"%>
	<div id="bodyColumn">
		<div id="contentBox">
		<h3>新建单源导入作业</h3>
			<center>
				<form action="<%=path%>/import3.jsp" method="post">
					<table align="center" style="width: 35%; margin: auto">
						<label hidden="true"><strong>导入源选项：</strong></label>
						<label hidden="true">数据库类型：</label>
						<input type="text" id="DBType" name="DBType" value="<%=DBType%>"
							hidden="true" />
						<label hidden="true">主机ip:</label>
						<input type="text" id="hostIp" name="hostIp" value="<%=hostIp%>"
							hidden="true" />
						<label hidden="true">端口号：</label>
						<input type="text" id="port" name="port" value="<%=port%>"
							hidden="true" />
						<label hidden="true">用户名：</label>
						<input type="text" id="DBUser" name="DBUser" value="<%=DBUser%>"
							hidden="true" />
						<label hidden="true">密码：</label>
						<input type="password" id="DBPassword" name="DBPassword"
							value="<%=DBPassword%>" hidden="true" />
						<label hidden="true">数据库名：</label>
						<input type="text" id="schema" name="schema" value="<%=schema%>"
							hidden="true" />
						<label hidden="true">表名：</label>
						<input type="text" id="tableName" name="tableName"
							value="<%=tableName%>" hidden="true" />
						<label hidden="true">where条件</label>
						<input type="text" id="where" name="where" value="<%=where%>"
							hidden="true" />

						<tr>
							<td><strong>二、导入目的选项</strong></td>
						</tr>
						<tr>
							<td></br></td>
						</tr>
						<tr>
							<td>导入位置：<input type="text" id="target" name="target" /></td>
						</tr>
						<tr>
							<td>列分隔符：<input type="text" id="columnSplit"
								name="columnSplit" /></td>
						</tr>
						<tr>
							<td>行分隔符：<input type="text" id="rowSplit" name="rowSplit" /></td>
						</tr>
						<tr>
							<td></br>
							<strong>其他</strong></td>
						</tr>
						<tr>
							<td>是否增量导入：<input type="radio" name="isIncremental"
								value="0" checked="checked" />否 <input type="radio"
								name="isIncremental" value="1" />是
							</td>
						</tr>
						<tr>
							<td></br>
							<input type="button" value="上一步" onclick="history.go(-1)" />&nbsp;&nbsp;&nbsp;&nbsp;
								<input type="submit" value="下一步" /></td>
						</tr>
					</table>
				</form>
			</center>
		</div>
	</div>
	<div class="clear">
		<hr />
	</div>
	<div id="footer">
		<div class="xright">
			&#169; 2016 South China Normal University - <a
				href="http://maven.apache.org/privacy-policy.html">Privacy
				Policy</a>
		</div>
		<div class="clear">
			<hr />
		</div>
	</div>
</body>
</html>