<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%
String path1 = request.getContextPath();
String basePath1 = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path1+"/";
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Generated by Apache Maven Doxia at 2016-11-13 -->
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>sqoop - Apache sqoop 2.6.0</title>
    <style type="text/css" media="all">
      @import url("./css/maven-base.css");
      @import url("./css/maven-theme.css");
      @import url("./css/site.css");
    </style>
    <link rel="stylesheet" href="./css/print.css" type="text/css" media="print" />
        <meta name="Date-Revision-yyyymmdd" content="20161113" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      </head>
  <body class="composite">
    <div id="leftColumn">
      <div id="navcolumn">
             <a href="<%=path1 %>/indexInfo"><h5>首页</h5></a>
                  <h5>新建作业</h5>
                  <ul>
                  <li class="none">
                  <a href="<%=path1 %>/import1.jsp">单源导入</a>
            </li>
            <li class="none">
                  <a href="<%=path1 %>/importMulti1.jsp">多源导入</a>
            </li>
            <li class="none">
                  <a href="<%=path1 %>/export1.jsp">导出</a>
            </li>
            <li class="none">
                  <a href="<%=path1 %>/hdfs1.jsp">hdfs数据迁移</a>
            </li>
          </ul>
                  <h5>作业状态</h5>
                  <ul>
                  <li class="none">
                  <a href="<%=path1 %>/runningJobList">运行中</a>
            </li>
            <li class="none">
                  <a href="<%=path1 %>/jobHistoryList">作业历史</a>
            </li>
             <li class="none">
                  <a href="<%=path1 %>/savedJobList">已保存作业</a>
            </li>
          </ul>
                       <h5>说明</h5>
                  <ul>
                  <li class="none">
                  <a href="<%=path1 %>/systemInstruction.jsp">系统说明</a>
            </li>
                  <li class="none">
                  <a href="<%=path1 %>/jobInstruction.jsp">作业说明</a>
            </li>
            <li class="none">
                  <a href="<%=path1 %>/operationInstruction.jsp">操作教程</a>
            </li>
          </ul>
                                 <a href="http://maven.apache.org/" title="Built by Maven" class="poweredBy">
          <img alt="Built by Maven" src="<%=path1 %>/images/logos/maven-feather.png"/>
        </a>
                       
                            </div>
    </div>
  </body>
</html>